controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

categorie_delete:
    path: /category/delete/{id}
    controller: App\Controller\CategoryController::delete
    requirements:
        id: \d+
